name: Trigger CI Pipeline

on:
    push:
        branches: [master]

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Get Short SHA
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Trigger Backend Build in CI
              run: |
                curl -X POST \
                -H "Authorization: token ${{ secrets.CI_TRIGGER_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/linfedCS/server-manager-deploy/dispatches \
                -d '{"event_type":"updater_build", "client_payload": {"ref": "${{ github.ref }}", "sha": "${{ steps.vars.outputs.sha_short }}"}}'
